export const TripStatus = {
    TRIP_SCHEDULED: "TRIP_SCHEDULED", 
    TRIP_CANCELLED: "TRIP_CANCELLED", 
    TRIP_SUCCESSFUL: "TRIP_SUCCESSFUL"
};

export const RideStatus = {
    REQUEST_PENDING: "REQUEST_PENDING", 
    REQUEST_ACCEPTED: "REQUEST_ACCEPTED", 
    REQUEST_DECLINED: "REQUEST_DECLINED", 
    REQUEST_CANCELLED: "REQUEST_CANCELLED", 
    RIDE_CANCELLED: "RIDE_CANCELLED", 
    RIDE_SUCCESSFUL: "RIDE_SUCCESSFUL", 
    RIDE_REMOVED: "RIDE_REMOVED"
    };